CREATE TABLE food_pairing (
    pairing_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wine_id INTEGER NOT NULL REFERENCES wine(wine_id),
    user_id INTEGER NOT NULL REFERENCES user_info(user_id),
    food_type TEXT NOT NULL,
    name TEXT NOT NULL,
    notes TEXT,
    img_url TEXT,
    source TEXT NOT NULL DEFAULT 'user_added',
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX food_pairing_wine_id_idx ON food_pairing(wine_id);
